import { CustomThemes } from '@openfin/workspace-platform';
import { CustomThemeOptions } from '@openfin/workspace-platform/common/src/api/theming';

const starterTheme: CustomThemeOptions = {
    label: 'Starter Theme (dark)',
    palette: {
        brandPrimary: "",
        brandSecondary: "",
        backgroundPrimary: "",
        functional1: "",
        functional2: "",
        functional3: "",
        functional4: "",
        functional5: "",
        functional6: "",
        functional7: "",
        functional8: "",
        functional9: "",
        functional10: "",
        statusSuccess: "",
        statusWarning: "",
        statusCritical: "",
        statusActive: "",
        inputBackground: "",
        inputColor: "",
        inputPlaceholder: "",
        inputDisabled: "",
        inputFocused: "",
        textDefault: "",
        textHelp: "",
        textInactive: "",
        background1: "",
        background2: "",
        background3: "",
        background4: "",
        background5: "",
        background6: "",
    },
};